{
 "title": "OTRS - Inicio",
 "description": "Overview of state of an Operations Service using OTRS as the main application",
 "time": { "from": "now/w", "to": "now/w" },
 "panels": [
  { "title": "Accesos Directos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Micro y Operaciones", "type": "dashlist", "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 } },
  { "title": "Sistemas", "type": "dashlist", "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 } },
  { "title": "Indicadores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Grupos UTE Iecisa/DMS",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(tn) from CESIC_Open\nwhere contar=1 and\nQueue<>'2 - Administración sistemas - Seguridad'"
    }
   ]
  },
  {
   "title": "Seguridad",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(tn) from CESIC_Open\nwhere contar=1 and\nQueue='2 - Administración sistemas - Seguridad'"
    }
   ]
  },
  {
   "title": "Microinformatica",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\nqueue as cola,\ncount(tn) as numero\nFROM otrs.CESIC_Open\nwhere \ntipo='Microinformatica'\ngroup by queue\norder by numero desc\n\n"
    }
   ]
  },
  {
   "title": "Sistemas",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\nqueue as cola,\ncount(tn) as numero\nFROM otrs.CESIC_Open\nwhere \ntipo='Administradores'\ngroup by queue\norder by numero desc\n\n"
    }
   ]
  },
  {
   "title": "Resueltos Micro",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select \ncount(tn) as num\nfrom ticket a left join dynamic_field_value g on (a.id=g.object_id and g.field_id=12), ticket_priority b, ticket_state c, ticket_type d, users e, queue f\nwhere \na.ticket_priority_id=b.id and\na.ticket_state_id=c.id and\na.type_id = d.id and\na.user_id=e.id and\na.queue_id = f.id and\na.queue_id in\n(\n130,\n168,\n160,\n162,\n80,\n261,\n120,\n81,\n121,\n109,\n166,\n98,\n122,\n205,\n260,\n2,\n159,\n233,\n185,\n325,\n329)\nand \na.ticket_state_id in (19,11,18);"
    }
   ]
  },
  {
   "title": "Resueltos Operaciones",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select \ncount(tn) as num\nfrom ticket a left join dynamic_field_value g on (a.id=g.object_id and g.field_id=12), ticket_priority b, ticket_state c, ticket_type d, users e, queue f\nwhere \na.ticket_priority_id=b.id and\na.ticket_state_id=c.id and\na.type_id = d.id and\na.user_id=e.id and\na.queue_id = f.id and\na.queue_id in\n(44,\n225,\n147,\n360,\n2)\nand \na.ticket_state_id in (19,11,18)\n;"
    }
   ]
  },
  {
   "title": "Resueltos Administradores",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select \ncount(tn) as num\nfrom ticket a left join dynamic_field_value g on (a.id=g.object_id and g.field_id=12), ticket_priority b, ticket_state c, ticket_type d, users e, queue f\nwhere \na.ticket_priority_id=b.id and\na.ticket_state_id=c.id and\na.type_id = d.id and\na.user_id=e.id and\na.queue_id = f.id and\na.queue_id in\n(\n231,\n232,\n128,\n45,\n46,\n47,\n62,\n230,\n48,\n125,\n127,\n195,\n126,\n49,\n194,\n51,\n52,\n55,\n228,\n57,\n139,\n457,\n63)\nand \na.ticket_state_id in (19,11,18)\n;\n"
    }
   ]
  },
  {
   "title": "Disponibilidad Global de los Servicios de IBSALUT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }
  },
  {
   "title": "Disponibilidad Global",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 25 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "Global",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "rawSql": "select \ncount(tn) as num\nfrom ticket a left join dynamic_field_value g on (a.id=g.object_id and g.field_id=12), ticket_priority b, ticket_state c, ticket_type d, users e, queue f\nwhere \na.ticket_priority_id=b.id and\na.ticket_state_id=c.id and\na.type_id = d.id and\na.user_id=e.id and\na.queue_id = f.id and\na.queue_id in\n(\n231,\n232,\n128,\n45,\n46,\n47,\n62,\n230,\n48,\n125,\n127,\n195,\n126,\n49,\n194,\n51,\n52,\n55,\n228,\n57,\n139,\n457,\n63)\nand \na.ticket_state_id in (19,11,18)\n;\n",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Historia Clinica",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 25 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "Historia Clinica",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "rawSql": "select \ncount(tn) as num\nfrom ticket a left join dynamic_field_value g on (a.id=g.object_id and g.field_id=12), ticket_priority b, ticket_state c, ticket_type d, users e, queue f\nwhere \na.ticket_priority_id=b.id and\na.ticket_state_id=c.id and\na.type_id = d.id and\na.user_id=e.id and\na.queue_id = f.id and\na.queue_id in\n(\n231,\n232,\n128,\n45,\n46,\n47,\n62,\n230,\n48,\n125,\n127,\n195,\n126,\n49,\n194,\n51,\n52,\n55,\n228,\n57,\n139,\n457,\n63)\nand \na.ticket_state_id in (19,11,18)\n;\n",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gestion de proveedores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 25 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "Gestion de proveedores",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "rawSql": "select \ncount(tn) as num\nfrom ticket a left join dynamic_field_value g on (a.id=g.object_id and g.field_id=12), ticket_priority b, ticket_state c, ticket_type d, users e, queue f\nwhere \na.ticket_priority_id=b.id and\na.ticket_state_id=c.id and\na.type_id = d.id and\na.user_id=e.id and\na.queue_id = f.id and\na.queue_id in\n(\n231,\n232,\n128,\n45,\n46,\n47,\n62,\n230,\n48,\n125,\n127,\n195,\n126,\n49,\n194,\n51,\n52,\n55,\n228,\n57,\n139,\n457,\n63)\nand \na.ticket_state_id in (19,11,18)\n;\n",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Portales institucionales",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 25 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "Portales institucionales",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "rawSql": "select \ncount(tn) as num\nfrom ticket a left join dynamic_field_value g on (a.id=g.object_id and g.field_id=12), ticket_priority b, ticket_state c, ticket_type d, users e, queue f\nwhere \na.ticket_priority_id=b.id and\na.ticket_state_id=c.id and\na.type_id = d.id and\na.user_id=e.id and\na.queue_id = f.id and\na.queue_id in\n(\n231,\n232,\n128,\n45,\n46,\n47,\n62,\n230,\n48,\n125,\n127,\n195,\n126,\n49,\n194,\n51,\n52,\n55,\n228,\n57,\n139,\n457,\n63)\nand \na.ticket_state_id in (19,11,18)\n;\n",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Sistemas administrativos",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 25 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "Sistemas Administrativos",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "rawSql": "select \ncount(tn) as num\nfrom ticket a left join dynamic_field_value g on (a.id=g.object_id and g.field_id=12), ticket_priority b, ticket_state c, ticket_type d, users e, queue f\nwhere \na.ticket_priority_id=b.id and\na.ticket_state_id=c.id and\na.type_id = d.id and\na.user_id=e.id and\na.queue_id = f.id and\na.queue_id in\n(\n231,\n232,\n128,\n45,\n46,\n47,\n62,\n230,\n48,\n125,\n127,\n195,\n126,\n49,\n194,\n51,\n52,\n55,\n228,\n57,\n139,\n457,\n63)\nand \na.ticket_state_id in (19,11,18)\n;\n",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Por tipo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Casos Totales por tipo",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT\ntype as tipo,\ncount(tn) as numero\nFROM otrs.CESIC_Open\nwhere \ncontar=1\ngroup by type\norder by type asc;\n\n"
    }
   ]
  },
  {
   "title": "Casos Abiertos por tipo",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT\ntype as tipo,\ncount(tn) as numero\nFROM otrs.CESIC_Open\nwhere \ncontar=1\nand estado in ('Abierto','Nuevo')\ngroup by type\norder by type asc;\n\n"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Evolucion apertura por horas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   queue.name as metric,\n count(tn) as value,\n  min(UNIX_TIMESTAMP(ticket.create_time)) as time_sec\n FROM ticket, queue\nWHERE  \nticket.create_time_unix>1483228800 and\nticket.queue_id = queue.id and\nticket.queue_id  in\n(2,\n44,\n45,\n46,\n47,\n48,\n49,\n51,\n52,\n55,\n57,\n62,\n80,\n81,\n98,\n120,\n121,\n122,\n125,\n126,\n127,\n128,\n130,\n147,\n168,\n194,\n195,\n205,\n228,\n230,\n231,\n232,\n260,\n360,\n160,\n225,\n261,\n139,\n162,\n233,\n109,\n166,\n159)\nand $__timeFilter(ticket.create_time)\nGROUP BY metric,UNIX_TIMESTAMP(ticket.create_time) DIV 1800"
    }
   ]
  }
 ]
}