{
 "title": "Dashboard Fortigates",
 "description": "Dashboard baseado em informações coletadas via SNMP no fortigate.\n",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Grupo", "query": "Firewall" },
   { "name": "Hosts", "query": "$Grupo.*" }
  ]
 },
 "panels": [
  {
   "title": "$Hosts - Alertas Zabbix",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": {
    "Noc Nacional": {
     "application": { "filter": "" },
     "group": { "filter": "Servidores Windows" },
     "host": { "filter": "$Hosts" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    "Truston": {
     "application": { "filter": "" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   }
  },
  {
   "title": "$Hosts - Número de Série",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 9, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Information(s)" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Device Serial Number" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$Hosts -  Status Vpn",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "application": { "filter": "VPN Tunnels" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/.*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$Hosts -  Versão do FortiOS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 9, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Information(s)" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "FortiOS version" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "HTTPS service is running" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Information(s)" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Uptime" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Ataques Bloqueados",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "IDS" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Number of intrusions blocked on virtual domain root"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$Hosts - Uso de CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/Media.*/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$Hosts - Memória Usada",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "System Memory Usage(%)" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$Hosts - Uso de Disco",
   "type": "graph",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "System" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Disk Capacity" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "System" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Disk Usage" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$Hosts - Trafego",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Interface(s)" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Trafego de Entrada na interface wan1"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interface(s)" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Trafego de Saída na interface wan1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interface(s)" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Trafego de Entrada na interface wan2"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interface(s)" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Trafego de Saída na interface wan2"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interface(s)" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Trafego de Entrada na interface wan"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interface(s)" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Trafego de Saída na interface wan"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}