{
 "title": "Dashboard Impressoras C35P",
 "description": "A ideia foi criar um dashboard com todos os dados gerenciais de impressoes.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Grupo", "query": "Grafana - Impressoras C35P" },
   { "name": "Hosts", "query": "$Grupo.*" }
  ]
 },
 "panels": [
  { "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 } },
  {
   "title": "Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Conectivity" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "ICMP Check" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Latência de Rede",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Conectivity" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Response Time" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Perda de Pacotes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "pps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Conectivity" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Packet Loss" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tempo de atividade",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "General" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Device uptime" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Impressões Totais",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Grafana - Impressoras C35P" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Impressões Totais" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Impressões Duplex",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Grafana - Impressoras C35P" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Impressões Duplex" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Nivel Toner Black",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Nível do Toner Black Real" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Nivel Toner Cyan",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Nível do Toner Cyan Real" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Nivel Toner Magenta",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Nível do Toner Magenta Real" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Nivel Toner Yellow",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Nível do Toner Yellow Real" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Impressões",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Grafana - Impressoras C35P" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Impressões Duplex" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "Grafana - Impressoras C35P" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Impressões Totais" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Unidade de Imagem",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Unidade de Imagem Black Real" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Unidade de Imagem",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Unidade de Imagem Cyan Real" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Unidade de Imagem",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Unidade de Imagem Magenta Real" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Unidade de Imagem",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Unidade de Imagem Yellow Real" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Correia de Transferência",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Correia de Transferencia Real" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Rolô de Transferência",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Rolo de Transferencia Real" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Unidade de Fusor",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Unidade de Fusor Real" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Recipiente de Toner",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Grafana - Impressoras C35P" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Recipiente de Toner cheio" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SLA Impressoras C35P",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Grafana - Impressoras C35P" },
     "host": { "filter": "$Hosts" },
     "itServiceFilter": "Impressoras Intesa C35P",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Alertas",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "targets": {
    "Zabbix": {
     "application": { "filter": "" },
     "group": { "filter": "Grafana - Impressoras C35P" },
     "host": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": {
      "filter": null
     }
    }
   }
  }
 ]
}