{
 "title": "Dashboard Nobreak",
 "description": "Monitoramento de Nobreak UPS Emerson",
 "tags": [
  "zabbix",
  "ups"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Nobreak SEDE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Estado da Bateria",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Battery" },
     "group": { "filter": "NoBreaks" },
     "host": { "filter": "Apcsede" },
     "item": { "filter": "Battery status" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Temperatura Sede",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 16, "x": 4, "y": 1 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Battery" },
     "group": { "filter": "NoBreaks" },
     "host": { "filter": "Apcsede" },
     "item": { "filter": "Battery temperature" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Status Testes no UPS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Battery" },
     "group": { "filter": "NoBreaks" },
     "host": { "filter": "Apcsede" },
     "item": { "filter": "Battery replacement status" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Carga da Bateria Sede",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Battery" },
     "group": { "filter": "NoBreaks" },
     "host": { "filter": "Apcsede" },
     "item": { "filter": "Battery charge" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ReponseTime Nobreak Sede",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "NoBreaks" },
     "host": { "filter": "Apcsede" },
     "item": { "filter": "ICMP response time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Bateria Restante Sede",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 9 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Battery" },
     "group": { "filter": "NoBreaks" },
     "host": { "filter": "Apcsede" },
     "item": { "filter": "Runtime remaining" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Ping Nobreak Sede",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "NoBreaks" },
     "host": { "filter": "Apcsede" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Nobreaks Datacenter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Temperatura Datacenter",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 20, "x": 2, "y": 16 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Battery" },
     "group": { "filter": "NoBreaks" },
     "host": { "filter": "Apc04 - Servidores" },
     "item": { "filter": "Battery temperature" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 19 },
   "content": "###                                                                                                    NOBREAK APC01"
  },
  {
   "title": "Carga da Bateria APC01",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Battery" },
     "group": { "filter": "NoBreaks" },
     "host": { "filter": "Apc01" },
     "item": { "filter": "Battery charge" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Bateria Restante APC01",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 21 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Battery" },
     "group": { "filter": "NoBreaks" },
     "host": { "filter": "Apc01" },
     "item": { "filter": "Runtime remaining" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ReponseTime Nobreak APC01",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "NoBreaks" },
     "host": { "filter": "Apc01" },
     "item": { "filter": "ICMP response time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Ping Nobreak APC01",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "NoBreaks" },
     "host": { "filter": "Apc01" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Estado da Bateria APC01",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 21 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Battery" },
     "group": { "filter": "NoBreaks" },
     "host": { "filter": "Apc01" },
     "item": { "filter": "Battery status" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Status Testes no UPS APC01",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Battery" },
     "group": { "filter": "NoBreaks" },
     "host": { "filter": "Apc01" },
     "item": { "filter": "Battery replacement status" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 27 },
   "content": "###                                                                                                    NOBREAK APC02"
  },
  {
   "title": "Carga da Bateria APC02",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 29 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Battery" },
     "group": { "filter": "NoBreaks" },
     "host": { "filter": "Apc02" },
     "item": { "filter": "Battery charge" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Bateria Restante APC02",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 29 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Battery" },
     "group": { "filter": "NoBreaks" },
     "host": { "filter": "Apc02" },
     "item": { "filter": "Runtime remaining" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ReponseTime Nobreak APC02",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "NoBreaks" },
     "host": { "filter": "Apc02" },
     "item": { "filter": "ICMP response time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Ping Nobreak APC02",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "NoBreaks" },
     "host": { "filter": "Apc02" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Estado da Bateria APC02",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 29 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Battery" },
     "group": { "filter": "NoBreaks" },
     "host": { "filter": "Apc02" },
     "item": { "filter": "Battery status" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Status Testes no UPS APC02",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Battery" },
     "group": { "filter": "NoBreaks" },
     "host": { "filter": "Apc02" },
     "item": { "filter": "Battery replacement status" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 35 },
   "content": "###                                                                                                    NOBREAK APC04"
  },
  {
   "title": "Carga da Bateria APC04",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 37 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Battery" },
     "group": { "filter": "NoBreaks" },
     "host": { "filter": "Apc04 - Servidores" },
     "item": { "filter": "Battery charge" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Bateria Restante APC04",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 37 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Battery" },
     "group": { "filter": "NoBreaks" },
     "host": { "filter": "Apc04 - Servidores" },
     "item": { "filter": "Runtime remaining" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ReponseTime Nobreak APC04",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "NoBreaks" },
     "host": { "filter": "Apc04 - Servidores" },
     "item": { "filter": "ICMP response time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Ping Nobreak APC04",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "NoBreaks" },
     "host": { "filter": "Apc04 - Servidores" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Estado da Bateria APC04",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 37 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Battery" },
     "group": { "filter": "NoBreaks" },
     "host": { "filter": "Apc04 - Servidores" },
     "item": { "filter": "Battery status" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Status Testes no UPS APC04",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 40 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Battery" },
     "group": { "filter": "NoBreaks" },
     "host": { "filter": "Apc04 - Servidores" },
     "item": { "filter": "Battery replacement status" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}