{
 "title": "Printer Xerox 7220",
 "description": "This is updated older version printer dashboard. For color A3 multifunction XEROX 7220 priner. ",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "WorkCentre 7220 SEKRETARIÁT", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 } },
  {
   "title": "Dostupnost",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Status" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Doba od posledního spuštění",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Printer information" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": { "filter": "Up Time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Celkem stran",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Pages printed" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "itServiceFilter": "/.*/",
     "item": { "filter": "Pages printed - total" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "Down time", "property": "downtimeTime" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 1,
      "count": true,
      "minSeverity": 5
     }
    }
   ]
  },
  {
   "title": "stran  Č/B",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Pages printed" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "itServiceFilter": "/.*/",
     "item": { "filter": "Pages printed - black" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "Down time", "property": "downtimeTime" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 1,
      "count": true,
      "minSeverity": 5
     }
    }
   ]
  },
  {
   "title": "stran barevně",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Pages printed" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "itServiceFilter": "/.*/",
     "item": { "filter": "Pages printed - color" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "Down time", "property": "downtimeTime" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 1,
      "count": true,
      "minSeverity": 5
     }
    }
   ]
  },
  {
   "title": "Dvouhodinová statistika",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Pages printed" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": { "filter": "Pages printed - color" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Pages printed" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": { "filter": "Pages printed - black" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Množství toneru při 5% pokrytí",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Consumables level" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/Current cartridge toner level -(.*)/",
        "$1"
       ],
       "text": "replaceAlias(/Current cartridge toner level -(.*)/, $1)"
      }
     ],
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": {
      "filter": "/Current cartridge toner level - */"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Odezva na ping",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Status" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": { "filter": "ICMP response time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Ztrátovost paketů",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 4 },
   "format": "pps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Status" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": { "filter": "ICMP loss" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Toner Black",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consumables level %" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": {
      "filter": "Cartridge toner level % - black"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Toner Cyan",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consumables level %" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": { "filter": "Cartridge toner level % - cyan" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Toner Yellow",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consumables level %" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": {
      "filter": "Cartridge toner level % - yellow"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Toner Magenta",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consumables level %" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": {
      "filter": "Cartridge toner level % - magenta"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Zásobník 1",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Printer information" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": { "filter": "Tray 1 - Media name" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Stav listů média",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Printer information" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": { "filter": "Tray 1 - Media current level" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Výstrahy - Xerox WorkCentre 7220",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": {
    "ZABBIX_DB": {
     "application": { "filter": "/.*/" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "tags": { "filter": "" },
     "trigger": { "filter": "/.*/" }
    },
    "Zabbix": {
     "application": { "filter": "/.*/" },
     "group": { "filter": "Grafana - Impressoras C284" },
     "host": { "filter": "/.*/" },
     "tags": { "filter": "" },
     "trigger": { "filter": "/.*/" }
    }
   }
  },
  {
   "title": "Drum U Black",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consumables level %" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": {
      "filter": "Current drum unit level % - black"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Drum U Cyan",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consumables level %" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": {
      "filter": "Current drum unit level % - cyan"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Drum U Yellow",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consumables level %" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": {
      "filter": "Current drum unit level % - yellow"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Drum U Magenta",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consumables level %" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": {
      "filter": "Current drum unit level % - magenta"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Zásobník 2",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Printer information" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": { "filter": "Tray 2 - Media name" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Stav listů média",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": { "filter": "Tray 2 - Media current level" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Statistika tisku",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 10 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": { "filter": "Pages printed - color" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": { "filter": "Pages printed - black" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Waste Toner Container",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consumables level %" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": { "filter": "Waste Toner Container %" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Fuser",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consumables level %" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": { "filter": "Fuser %" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Transfer Belt",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consumables level %" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": { "filter": "Transfer Belt Cleaner %" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Bias Transfer Roll",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consumables level %" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": { "filter": "Second Bias Transfer Roller %" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Zásobník 5 - manuální",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Printer information" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": { "filter": "Tray 5 manual - Media name" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Stav listů média",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": {
      "filter": "Tray 5 manual - Media current level"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "24 hodinová statistika",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "application": { "filter": "Pages printed" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": { "filter": "Pages printed - black" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Pages printed" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": { "filter": "Pages printed - color" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "7 denní statistika",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "application": { "filter": "Pages printed" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": { "filter": "Pages printed - black" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Pages printed" },
     "group": { "filter": "Printers" },
     "host": { "filter": "WorkCentre 7220" },
     "item": { "filter": "Pages printed - color" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}