{
 "title": "Status Microsoft Windows WSUS",
 "description": "Este dashboard foi construido para dar visibilidade para os principais itens do serviço Microsoft WSUS.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<div align=\"center\"><h3>WSUS CASAS</H3></div>"
  },
  {
   "title": "Number of known clients",
   "type": "graph",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CSC-SP" ],
       "text": "setAlias(CSC-SP)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "CSCSP-PWSUS1" },
     "item": { "filter": "Number of known clients" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CSSJ" ],
       "text": "setAlias(CSSJ)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "CSSJ-PWSUS" },
     "item": { "filter": "Number of known clients" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HEC" ],
       "text": "setAlias(HEC)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HECSRVWSUS" },
     "item": { "filter": "Number of known clients" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HMRP" ],
       "text": "setAlias(HMRP)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HMRPSRVWSUS" },
     "item": { "filter": "Number of known clients" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HSC" ],
       "text": "setAlias(HSC)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HSC-WSUS-VM" },
     "item": { "filter": "Number of known clients" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HSI" ],
       "text": "setAlias(HSI)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HSI-WSUS1" },
     "item": { "filter": "Number of known clients" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HSL" ],
       "text": "setAlias(HSL)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HSLSRVWSUS" },
     "item": { "filter": "Number of known clients" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HST" ],
       "text": "setAlias(HST)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HST-PWSUS" },
     "item": { "filter": "Number of known clients" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Alertas",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
   "targets": {
    "ZABBIX": {
     "application": { "filter": "//" },
     "group": { "filter": "WSUS" },
     "host": { "filter": "//" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   }
  },
  {
   "title": "Number of clients updated with fails",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CSCSP-PWSUS1" ],
       "text": "setAlias(CSCSP-PWSUS1)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "CSCSP-PWSUS1" },
     "item": {
      "filter": "Number of clients updated with fails"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CSCSP-PWSUS1" ],
       "text": "setAlias(CSCSP-PWSUS1)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "CSSJ-PWSUS" },
     "item": {
      "filter": "Number of clients updated with fails"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HECSRVWSUS" ],
       "text": "setAlias(HECSRVWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HECSRVWSUS" },
     "item": {
      "filter": "Number of clients updated with fails"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HMRPSRVWSUS" ],
       "text": "setAlias(HMRPSRVWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HMRPSRVWSUS" },
     "item": {
      "filter": "Number of clients updated with fails"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HSC-WSUS-VM" ],
       "text": "setAlias(HSC-WSUS-VM)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HSC-WSUS-VM" },
     "item": {
      "filter": "Number of clients updated with fails"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HSI-WSUS1" ],
       "text": "setAlias(HSI-WSUS1)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HSI-WSUS1" },
     "item": {
      "filter": "Number of clients updated with fails"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HSLSRVWSUS" ],
       "text": "setAlias(HSLSRVWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HSLSRVWSUS" },
     "item": {
      "filter": "Number of clients updated with fails"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HST-PWSUS" ],
       "text": "setAlias(HST-PWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HST-PWSUS" },
     "item": {
      "filter": "Number of clients updated with fails"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Number of full updated clients",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CSCSP-PWSUS1" ],
       "text": "setAlias(CSCSP-PWSUS1)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "CSCSP-PWSUS1" },
     "item": { "filter": "Number of full updated clients" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CSCSP-PWSUS1" ],
       "text": "setAlias(CSCSP-PWSUS1)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "CSSJ-PWSUS" },
     "item": { "filter": "Number of full updated clients" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HECSRVWSUS" ],
       "text": "setAlias(HECSRVWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HECSRVWSUS" },
     "item": { "filter": "Number of full updated clients" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HMRPSRVWSUS" ],
       "text": "setAlias(HMRPSRVWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HMRPSRVWSUS" },
     "item": { "filter": "Number of full updated clients" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HSC-WSUS-VM" ],
       "text": "setAlias(HSC-WSUS-VM)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HSC-WSUS-VM" },
     "item": { "filter": "Number of full updated clients" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HSI-WSUS1" ],
       "text": "setAlias(HSI-WSUS1)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HSI-WSUS1" },
     "item": { "filter": "Number of full updated clients" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HSLSRVWSUS" ],
       "text": "setAlias(HSLSRVWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HSLSRVWSUS" },
     "item": { "filter": "Number of full updated clients" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HST-PWSUS" ],
       "text": "setAlias(HST-PWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HST-PWSUS" },
     "item": { "filter": "Number of full updated clients" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Number of clients updated with fails",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CSCSP-PWSUS1" ],
       "text": "setAlias(CSCSP-PWSUS1)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "CSCSP-PWSUS1" },
     "item": {
      "filter": "Number of clients updated with fails"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CSCSP-PWSUS1" ],
       "text": "setAlias(CSCSP-PWSUS1)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "CSSJ-PWSUS" },
     "item": {
      "filter": "Number of clients updated with fails"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HECSRVWSUS" ],
       "text": "setAlias(HECSRVWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HECSRVWSUS" },
     "item": {
      "filter": "Number of clients updated with fails"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HMRPSRVWSUS" ],
       "text": "setAlias(HMRPSRVWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HMRPSRVWSUS" },
     "item": {
      "filter": "Number of clients updated with fails"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HSC-WSUS-VM" ],
       "text": "setAlias(HSC-WSUS-VM)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HSC-WSUS-VM" },
     "item": {
      "filter": "Number of clients updated with fails"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HSI-WSUS1" ],
       "text": "setAlias(HSI-WSUS1)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HSI-WSUS1" },
     "item": {
      "filter": "Number of clients updated with fails"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HSLSRVWSUS" ],
       "text": "setAlias(HSLSRVWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HSLSRVWSUS" },
     "item": {
      "filter": "Number of clients updated with fails"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HST-PWSUS" ],
       "text": "setAlias(HST-PWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HST-PWSUS" },
     "item": {
      "filter": "Number of clients updated with fails"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Number of partially updated clients",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CSCSP-PWSUS1" ],
       "text": "setAlias(CSCSP-PWSUS1)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "CSCSP-PWSUS1" },
     "item": {
      "filter": "Number of partially updated clients"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CSCSP-PWSUS1" ],
       "text": "setAlias(CSCSP-PWSUS1)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "CSSJ-PWSUS" },
     "item": {
      "filter": "Number of partially updated clients"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HECSRVWSUS" ],
       "text": "setAlias(HECSRVWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HECSRVWSUS" },
     "item": {
      "filter": "Number of partially updated clients"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HMRPSRVWSUS" ],
       "text": "setAlias(HMRPSRVWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HMRPSRVWSUS" },
     "item": {
      "filter": "Number of partially updated clients"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HSC-WSUS-VM" ],
       "text": "setAlias(HSC-WSUS-VM)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HSC-WSUS-VM" },
     "item": {
      "filter": "Number of partially updated clients"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HSI-WSUS1" ],
       "text": "setAlias(HSI-WSUS1)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HSI-WSUS1" },
     "item": {
      "filter": "Number of partially updated clients"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HSLSRVWSUS" ],
       "text": "setAlias(HSLSRVWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HSLSRVWSUS" },
     "item": {
      "filter": "Number of partially updated clients"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HST-PWSUS" ],
       "text": "setAlias(HST-PWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HST-PWSUS" },
     "item": {
      "filter": "Number of partially updated clients"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "NETWORK INTERFACES IN",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CSCSP-PWSUS1" ],
       "text": "setAlias(CSCSP-PWSUS1)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "CSCSP-PWSUS1" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CSSJ-PWSUS" ],
       "text": "setAlias(CSSJ-PWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "CSSJ-PWSUS" },
     "item": {
      "filter": "Incoming network traffic on vmxnet3 Ethernet Adapter"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HECSRVWSUS" ],
       "text": "setAlias(HECSRVWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HECSRVWSUS" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HMRPSRVWSUS" ],
       "text": "setAlias(HMRPSRVWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HMRPSRVWSUS" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HSC-WSUS-VM" ],
       "text": "setAlias(HSC-WSUS-VM)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HSC-WSUS-VM" },
     "item": {
      "filter": "Incoming network traffic on vmxnet3 Ethernet Adapter"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HSI-WSUS1" ],
       "text": "setAlias(HSI-WSUS1)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HSI-WSUS1" },
     "item": {
      "filter": "Incoming network traffic on vmxnet3 Ethernet Adapter"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HSLSRVWSUS" ],
       "text": "setAlias(HSLSRVWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HSLSRVWSUS" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HSLSRVWSUS" ],
       "text": "setAlias(HSLSRVWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HSLSRVWSUS" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HST-PWSUS" ],
       "text": "setAlias(HST-PWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HST-PWSUS" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Number of updates that are needed by one or more client computers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CSC-SP" ],
       "text": "setAlias(CSC-SP)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "CSCSP-PWSUS1" },
     "item": {
      "filter": "Number of updates that are needed by one or more client computers"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CSSJ" ],
       "text": "setAlias(CSSJ)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "CSSJ-PWSUS" },
     "item": {
      "filter": "Number of updates that are needed by one or more client computers"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HEC" ],
       "text": "setAlias(HEC)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HECSRVWSUS" },
     "item": {
      "filter": "Number of updates that are needed by one or more client computers"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HMRP" ],
       "text": "setAlias(HMRP)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HMRPSRVWSUS" },
     "item": {
      "filter": "Number of updates that are needed by one or more client computers"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HSC" ],
       "text": "setAlias(HSC)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HSC-WSUS-VM" },
     "item": {
      "filter": "Number of updates that are needed by one or more client computers"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HSI" ],
       "text": "setAlias(HSI)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HSI-WSUS1" },
     "item": {
      "filter": "Number of updates that are needed by one or more client computers"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HSL" ],
       "text": "setAlias(HSL)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HSLSRVWSUS" },
     "item": {
      "filter": "Number of updates that are needed by one or more client computers"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HST" ],
       "text": "setAlias(HST)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HST-PWSUS" },
     "item": {
      "filter": "Number of updates that are needed by one or more client computers"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "NETWORK INTERFACES OUT",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CSCSP-PWSUS1" ],
       "text": "setAlias(CSCSP-PWSUS1)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "CSCSP-PWSUS1" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CSSJ-PWSUS" ],
       "text": "setAlias(CSSJ-PWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "CSSJ-PWSUS" },
     "item": {
      "filter": "Outgoing network traffic on vmxnet3 Ethernet Adapter"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HECSRVWSUS" ],
       "text": "setAlias(HECSRVWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HECSRVWSUS" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HMRPSRVWSUS" ],
       "text": "setAlias(HMRPSRVWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HMRPSRVWSUS" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HSC-WSUS-VM" ],
       "text": "setAlias(HSC-WSUS-VM)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HSC-WSUS-VM" },
     "item": {
      "filter": "Outgoing network traffic on vmxnet3 Ethernet Adapter"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HSI-WSUS1" ],
       "text": "setAlias(HSI-WSUS1)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HSI-WSUS1" },
     "item": {
      "filter": "Outgoing network traffic on vmxnet3 Ethernet Adapter"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HSLSRVWSUS" ],
       "text": "setAlias(HSLSRVWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HSLSRVWSUS" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HSLSRVWSUS" ],
       "text": "setAlias(HSLSRVWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HSLSRVWSUS" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HST-PWSUS" ],
       "text": "setAlias(HST-PWSUS)"
      }
     ],
     "group": { "filter": "WSUS" },
     "host": { "filter": "HST-PWSUS" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}