{
 "title": "TERMINAL SERVER",
 "description": "Dashboard  Terminal Server",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "content": "<center><img width=\"250\" height=\"175\" src=\"https://www.loadbalancer.org/public/images/articles/2015/07/terminal-services-logo.png \">\n"
  },
  {
   "title": "Numero de processos no sistema",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Processos" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "Número de processos" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Taxa de leitura em disco por segundo",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Performance" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "Arquivo lido bytes por segundo" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Comprimento médio da fila de leitura de disco",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Performance" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": {
      "filter": "Comprimento médio da fila de leitura de disco"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Usuários Ativos Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "RDP Terminal Server" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "Usuários Ativos Total" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "UPTIME",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 2 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Geral" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "Tempo de atividade do sistema" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Taxa de escrita em disco por segundo",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 2 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Performance" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": {
      "filter": "Bytes de gravação de arquivo por segundo"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Comprimento médio da fila de gravação em disco",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 2 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Performance" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": {
      "filter": "Comprimento médio da fila de gravação em disco"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Usuários Inativos Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "RDP Terminal Server" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "Usuários Inativos Total" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "% Uso de Memória",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
   "format": "percent",
   "targets": [
    {
     "application": { "filter": "Memória" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "Memória em Uso(%)" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free memory",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memória" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "Memória disponível" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Memória" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "Memória em Uso" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Espaço Livre em C:",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 5 },
   "format": "percent",
   "targets": [
    {
     "application": { "filter": "Sistema de Arquivos" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": {
      "filter": "Free disk space on C: (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Espaço Livre em D:",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 5 },
   "format": "percent",
   "targets": [
    {
     "application": { "filter": "Sistema de Arquivos" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": {
      "filter": "Free disk space on D: (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Remote Desktop Licensing Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "RDP Terminal Server" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "Remote Desktop Services" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Remote Desktop Licensing Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "RDP Terminal Server" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "Remote Desktop Licensing" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Porta TS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "Porta" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces de Rede" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": {
      "filter": "Tráfego Entrada vmxnet3 Ethernet Adapter"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interfaces de Rede" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": {
      "filter": "Tráfego Saída vmxnet3 Ethernet Adapter"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "Uso de CPU (média 1 min)" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "Uso de CPU (média 5 min)" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "Uso de CPU (média 15 min)" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}