{
 "title": "Zabbix Host Status",
 "description": "Status of a server monitored by zabbix agent",
 "tags": [
  "zabbix",
  "agent",
  "system"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "group", "query": "*" },
   { "name": "host", "query": "$group.*" }
  ]
 },
 "panels": [
  { "title": "Host Information", "type": "text", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 }, "content": "## $group - $host" },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "alias": "System uptime",
     "application": {
      "filter": "",
      "isRegex": false,
      "name": "General",
      "style": {}
     },
     "downsampleFunction": { "name": "max", "value": "max" },
     "group": {
      "filter": "$group",
      "isRegex": false,
      "name": "$group",
      "style": {},
      "templated": true
     },
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "host": {
      "filter": "$host",
      "isRegex": false,
      "name": "$host",
      "style": {},
      "templated": true
     },
     "item": {
      "filter": "System uptime",
      "isRegex": false,
      "name": "System uptime",
      "style": {}
     },
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Processor load (1 min average per core)",
     "application": {
      "filter": "",
      "isRegex": false,
      "name": "Performance",
      "style": {}
     },
     "downsampleFunction": { "name": "avg", "value": "avg" },
     "group": {
      "filter": "$group",
      "isRegex": false,
      "name": "$group",
      "style": {},
      "templated": true
     },
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "host": {
      "filter": "$host",
      "isRegex": false,
      "name": "$host",
      "style": {},
      "templated": true
     },
     "item": {
      "filter": "Processor load (1 min average per core)",
      "isRegex": false,
      "name": "Processor load (1 min average per core)",
      "style": {}
     },
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "Available memory",
     "application": { "name": "Memory" },
     "downsampleFunction": { "name": "avg", "value": "avg" },
     "group": {
      "filter": "$group",
      "isRegex": false,
      "name": "$group",
      "style": {},
      "templated": true
     },
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "host": {
      "filter": "$host",
      "isRegex": false,
      "name": "$host",
      "style": {},
      "templated": true
     },
     "item": {
      "filter": "Available memory",
      "isRegex": false,
      "name": "Available memory",
      "style": {}
     },
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of processes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Number of processes",
     "application": { "name": "Processes" },
     "downsampleFunction": { "name": "avg", "value": "avg" },
     "group": {
      "filter": "$group",
      "isRegex": false,
      "name": "$group",
      "style": {},
      "templated": true
     },
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "host": {
      "filter": "$host",
      "isRegex": false,
      "name": "$host",
      "style": {},
      "templated": true
     },
     "item": {
      "filter": "Number of processes",
      "isRegex": false,
      "name": "Number of processes",
      "style": {}
     },
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Logged in Users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Number of logged in users",
     "application": { "name": "Security" },
     "downsampleFunction": { "name": "max", "value": "max" },
     "group": {
      "filter": "$group",
      "isRegex": false,
      "name": "$group",
      "style": {},
      "templated": true
     },
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "host": {
      "filter": "$host",
      "isRegex": false,
      "name": "$host",
      "style": {},
      "templated": true
     },
     "item": {
      "filter": "Number of logged in users",
      "isRegex": false,
      "name": "Number of logged in users",
      "style": {}
     },
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Triggers",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "targets": {
    "cadran_zabbix": {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    "zabbix": {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   }
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "iowait",
     "application": { "name": "CPU" },
     "downsampleFunction": { "name": "avg", "value": "avg" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "iowait" ],
       "text": "setAlias(iowait)"
      }
     ],
     "group": {
      "filter": "$group",
      "isRegex": false,
      "name": "$group",
      "style": {},
      "templated": true
     },
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "host": {
      "filter": "$host",
      "isRegex": false,
      "name": "$host",
      "style": {},
      "templated": true
     },
     "item": {
      "filter": "CPU iowait time",
      "isRegex": false,
      "name": "CPU iowait time",
      "style": {}
     },
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "user",
     "application": { "name": "CPU" },
     "downsampleFunction": { "name": "avg", "value": "avg" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "system" ],
       "text": "setAlias(system)"
      }
     ],
     "group": {
      "filter": "$group",
      "isRegex": false,
      "name": "$group",
      "style": {},
      "templated": true
     },
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "host": {
      "filter": "$host",
      "isRegex": false,
      "name": "$host",
      "style": {},
      "templated": true
     },
     "item": {
      "filter": "CPU system time",
      "isRegex": false,
      "name": "CPU user time",
      "style": {}
     },
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "system",
     "application": { "name": "CPU" },
     "downsampleFunction": { "name": "avg", "value": "avg" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "user" ],
       "text": "setAlias(user)"
      }
     ],
     "group": {
      "filter": "$group",
      "isRegex": false,
      "name": "$group",
      "style": {},
      "templated": true
     },
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "host": {
      "filter": "$host",
      "isRegex": false,
      "name": "$host",
      "style": {},
      "templated": true
     },
     "item": {
      "filter": "CPU user time",
      "isRegex": false,
      "name": "CPU system time",
      "style": {}
     },
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "idle",
     "application": { "name": "CPU" },
     "downsampleFunction": { "name": "avg", "value": "avg" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "steal" ],
       "text": "setAlias(steal)"
      }
     ],
     "group": {
      "filter": "$group",
      "isRegex": false,
      "name": "$group",
      "style": {},
      "templated": true
     },
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "host": {
      "filter": "$host",
      "isRegex": false,
      "name": "$host",
      "style": {},
      "templated": true
     },
     "item": {
      "filter": "CPU steal time",
      "isRegex": false,
      "name": "CPU idle time",
      "style": {}
     },
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "idle",
     "application": { "name": "CPU" },
     "downsampleFunction": { "name": "avg", "value": "avg" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "interrupt" ],
       "text": "setAlias(interrupt)"
      }
     ],
     "group": {
      "filter": "$group",
      "isRegex": false,
      "name": "$group",
      "style": {},
      "templated": true
     },
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "host": {
      "filter": "$host",
      "isRegex": false,
      "name": "$host",
      "style": {},
      "templated": true
     },
     "item": {
      "filter": "CPU interrupt time",
      "isRegex": false,
      "name": "CPU idle time",
      "style": {}
     },
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "idle",
     "application": { "name": "CPU" },
     "downsampleFunction": { "name": "avg", "value": "avg" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "nice" ],
       "text": "setAlias(nice)"
      }
     ],
     "group": {
      "filter": "$group",
      "isRegex": false,
      "name": "$group",
      "style": {},
      "templated": true
     },
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "host": {
      "filter": "$host",
      "isRegex": false,
      "name": "$host",
      "style": {},
      "templated": true
     },
     "item": {
      "filter": "CPU nice time",
      "isRegex": false,
      "name": "CPU idle time",
      "style": {}
     },
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "idle",
     "application": { "name": "CPU" },
     "downsampleFunction": { "name": "avg", "value": "avg" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "idle" ],
       "text": "setAlias(idle)"
      }
     ],
     "group": {
      "filter": "$group",
      "isRegex": false,
      "name": "$group",
      "style": {},
      "templated": true
     },
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "host": {
      "filter": "$host",
      "isRegex": false,
      "name": "$host",
      "style": {},
      "templated": true
     },
     "item": {
      "filter": "CPU idle time",
      "isRegex": false,
      "name": "CPU idle time",
      "style": {}
     },
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Available memory",
     "application": { "name": "Memory" },
     "downsampleFunction": { "name": "avg", "value": "avg" },
     "group": {
      "filter": "$group",
      "isRegex": false,
      "name": "$group",
      "style": {},
      "templated": true
     },
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "host": {
      "filter": "$host",
      "isRegex": false,
      "name": "$host",
      "style": {},
      "templated": true
     },
     "item": {
      "filter": "/.*memory/",
      "isRegex": false,
      "name": "Available memory",
      "style": {}
     },
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free Swap %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Free swap space in %",
     "application": { "name": "Memory" },
     "downsampleFunction": { "name": "avg", "value": "avg" },
     "group": {
      "filter": "$group",
      "isRegex": false,
      "name": "$group",
      "style": {},
      "templated": true
     },
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "host": {
      "filter": "$host",
      "isRegex": false,
      "name": "$host",
      "style": {},
      "templated": true
     },
     "item": {
      "filter": "Free swap space in %",
      "isRegex": false,
      "name": "Free swap space in %",
      "style": {}
     },
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processor Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "1 min average",
     "application": { "name": "Performance" },
     "downsampleFunction": { "name": "avg", "value": "avg" },
     "group": {
      "filter": "$group",
      "isRegex": false,
      "name": "$group",
      "style": {},
      "templated": true
     },
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "host": {
      "filter": "$host",
      "isRegex": false,
      "name": "$host",
      "style": {},
      "templated": true
     },
     "item": {
      "filter": "Processor load (1 min average per core)",
      "isRegex": false,
      "name": "Processor load (1 min average per core)",
      "style": {}
     },
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "5 min average",
     "application": { "name": "Performance" },
     "downsampleFunction": { "name": "avg", "value": "avg" },
     "group": {
      "filter": "$group",
      "isRegex": false,
      "name": "$group",
      "style": {},
      "templated": true
     },
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "host": {
      "filter": "$host",
      "isRegex": false,
      "name": "$host",
      "style": {},
      "templated": true
     },
     "item": {
      "filter": "Processor load (5 min average per core)",
      "isRegex": false,
      "name": "Processor load (5 min average per core)",
      "style": {}
     },
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "15 min average",
     "application": { "name": "Performance" },
     "downsampleFunction": { "name": "avg", "value": "avg" },
     "group": {
      "filter": "$group",
      "isRegex": false,
      "name": "$group",
      "style": {},
      "templated": true
     },
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "host": {
      "filter": "$host",
      "isRegex": false,
      "name": "$host",
      "style": {},
      "templated": true
     },
     "item": {
      "filter": "Processor load (15 min average per core)",
      "isRegex": false,
      "name": "Processor load (15 min average per core)",
      "style": {}
     },
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Traffic on eth0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "In eth0",
     "application": { "name": "Network interfaces" },
     "downsampleFunction": { "name": "avg", "value": "avg" },
     "group": {
      "filter": "$group",
      "isRegex": false,
      "name": "$group",
      "style": {},
      "templated": true
     },
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "host": {
      "filter": "$host",
      "isRegex": false,
      "name": "$host",
      "style": {},
      "templated": true
     },
     "item": {
      "filter": "Incoming network traffic on eth0",
      "isRegex": false,
      "name": "Incoming network traffic on eth0",
      "style": {}
     },
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Out eth0",
     "application": { "name": "Network interfaces" },
     "downsampleFunction": { "name": "avg", "value": "avg" },
     "group": {
      "filter": "$group",
      "isRegex": false,
      "name": "$group",
      "style": {},
      "templated": true
     },
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "host": {
      "filter": "$host",
      "isRegex": false,
      "name": "$host",
      "style": {},
      "templated": true
     },
     "item": {
      "filter": "Outgoing network traffic on eth0",
      "isRegex": false,
      "name": "Outgoing network traffic on eth0",
      "style": {}
     },
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IO/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$group" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "$host" },
     "item": { "filter": "Read Operations / sec" },
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$group" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "$host" },
     "item": { "filter": "Write operations / sec" },
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Filesystems",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "In eth0",
     "application": { "filter": "Filesystems", "name": "Network interfaces" },
     "downsampleFunction": { "name": "avg", "value": "avg" },
     "group": {
      "filter": "$group",
      "isRegex": false,
      "name": "$group",
      "style": {},
      "templated": true
     },
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "host": {
      "filter": "$host",
      "isRegex": false,
      "name": "$host",
      "style": {},
      "templated": true
     },
     "item": {
      "filter": "Free disk space on /var (percentage)",
      "isRegex": false,
      "name": "Incoming network traffic on eth0",
      "style": {}
     },
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}